[metadata]
name = mempost
version = 1.0.0
author = Ali Siahkoohi
author_email = alisk@ucf.edu
description = Posterior under memorized diffusion priors
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
install_requires =
    numpy
    scipy
    matplotlib
    h5py
    tqdm
    torch
    projorg
    grf
packages = find:
python_requires = >=3.9

[options.extras_require]
seismic =
    diffusers
    devito
test =
    pytest

[options.packages.find]
exclude =
    tests*
    scripts*
    data*
    plots*
    figs*
